chains:
- chain_number: 1
  estimated_duration_seconds: 5.0
  estimated_file_size_mb: 0.91552734375
  max_samples_per_chain: 16
  sample_count: 5
  total_files: 5
  type: regular
configuration:
  max_samples_per_chain: 16
