"""
Real audio library directory structure for testing.

This module contains the actual directory structure from a real audio library
to provide realistic test data for the AudioDirectoryAnalyzer.
"""

from pathlib import Path
from typing import List, Dict, Any


def get_real_audio_library_structure() -> List[str]:
    """
    Returns the actual directory structure from a real audio library.
    
    This is the exact output from 'find .' command on the user's audio library.
    Each line represents a file or directory path.
    
    Returns:
        List[str]: List of file/directory paths
    """
    return [
        "./Drums",
        "./Drums/.DS_Store",
        "./Drums/Clap",
        "./Drums/Clap/Clap Aberlour.wav",
        "./Drums/Clap/Clap Antimax.wav",
        "./Drums/Clap/Clap Beach.wav",
        "./Drums/Clap/Clap Berg.wav",
        "./Drums/Clap/Clap Betaine.wav",
        "./Drums/Clap/Clap Bon Voyage.wav",
        "./Drums/Clap/Clap Brownie.wav",
        "./Drums/Clap/Clap Bueh.wav",
        "./Drums/Clap/Clap Can.wav",
        "./Drums/Clap/Clap Data.wav",
        "./Drums/Clap/Clap Fruit.wav",
        "./Drums/Clap/Clap Function.wav",
        "./Drums/Clap/Clap Geiger.wav",
        "./Drums/Clap/Clap Globuli.wav",
        "./Drums/Clap/Clap MmmKay 1.wav",
        "./Drums/Clap/Clap MmmKay 2.wav",
        "./Drums/Clap/Clap Moon.wav",
        "./Drums/Clap/Clap Normandy.wav",
        "./Drums/Clap/Clap Otherwood.wav",
        "./Drums/Clap/Clap Pre-Fade.wav",
        "./Drums/Clap/Clap PrisonerS.wav",
        "./Drums/Clap/Clap Quarter.wav",
        "./Drums/Clap/Clap Runzel.wav",
        "./Drums/Clap/Clap Salad.wav",
        "./Drums/Clap/Clap Schrumpf.wav",
        "./Drums/Clap/Clap Singleton.wav",
        "./Drums/Clap/Clap Strom.wav",
        "./Drums/Clap/Clap Together.wav",
        "./Drums/Clap/Clap XOR.wav",
        "./Drums/Clap/Clap Zee.wav",
        "./Drums/Cymbal",
        "./Drums/Cymbal/Cymbal Brownie.wav",
        "./Drums/Cymbal/Ride Berg.wav",
        "./Drums/Cymbal/Ride Fruit.wav",
        "./Drums/Hihat",
        "./Drums/Hihat/ClosedHH Aberlour 1.wav",
        "./Drums/Hihat/ClosedHH Aberlour 2.wav",
        "./Drums/Hihat/ClosedHH Antimax 01.wav",
        "./Drums/Hihat/ClosedHH Antimax 02.wav",
        "./Drums/Hihat/ClosedHH Antimax 03.wav",
        "./Drums/Hihat/ClosedHH Beach 1.wav",
        "./Drums/Hihat/ClosedHH Beach 2.wav",
        "./Drums/Hihat/ClosedHH Berg 1.wav",
        "./Drums/Hihat/ClosedHH Berg 2.wav",
        "./Drums/Hihat/ClosedHH Betaine 1.wav",
        "./Drums/Hihat/ClosedHH Betaine 2.wav",
        "./Drums/Hihat/ClosedHH Bon Voyage 1.wav",
        "./Drums/Hihat/ClosedHH Brownie 1.wav",
        "./Drums/Hihat/ClosedHH Brownie 2.wav",
        "./Drums/Hihat/ClosedHH Bueh 1.wav",
        "./Drums/Hihat/ClosedHH Bueh 2.wav",
        "./Drums/Hihat/ClosedHH Data 1.wav",
        "./Drums/Hihat/ClosedHH Data 2.wav",
        "./Drums/Hihat/ClosedHH Fruit 1.wav",
        "./Drums/Hihat/ClosedHH Fruit 2.wav",
        "./Drums/Hihat/ClosedHH Fruit 3.wav",
        "./Drums/Hihat/ClosedHH Geiger 1.wav",
        "./Drums/Hihat/ClosedHH Geiger 2.wav",
        "./Drums/Hihat/ClosedHH Globuli.wav",
        "./Drums/Hihat/ClosedHH MmmKay 1.wav",
        "./Drums/Hihat/ClosedHH MmmKay 2.wav",
        "./Drums/Hihat/ClosedHH Moon 1.wav",
        "./Drums/Hihat/ClosedHH Moon 2.wav",
        "./Drums/Hihat/ClosedHH Moon 3.wav",
        "./Drums/Hihat/ClosedHH Normandy Combo.wav",
        "./Drums/Hihat/ClosedHH Normandy.wav",
        "./Drums/Hihat/ClosedHH Pre-Fade 1.wav",
        "./Drums/Hihat/ClosedHH Pre-Fade 2.wav",
        "./Drums/Hihat/ClosedHH Quarter 1.wav",
        "./Drums/Hihat/ClosedHH Quarter 2.wav",
        "./Drums/Hihat/ClosedHH Runzel 1.wav",
        "./Drums/Hihat/ClosedHH Runzel 2.wav",
        "./Drums/Hihat/ClosedHH Salad 1.wav",
        "./Drums/Hihat/ClosedHH Salad 2.wav",
        "./Drums/Hihat/ClosedHH Schrumpf 1.wav",
        "./Drums/Hihat/ClosedHH Schrumpf 2.wav",
        "./Drums/Hihat/ClosedHH Singleton 01.wav",
        "./Drums/Hihat/ClosedHH Singleton 02.wav",
        "./Drums/Hihat/ClosedHH Strom 1.wav",
        "./Drums/Hihat/ClosedHH Strom 2.wav",
        "./Drums/Hihat/ClosedHH Together 1.wav",
        "./Drums/Hihat/ClosedHH Together 2.wav",
        "./Drums/Hihat/ClosedHH XOR 1.wav",
        "./Drums/Hihat/ClosedHH XOR 2.wav",
        "./Drums/Hihat/ClosedHH XOR 3.wav",
        "./Drums/Hihat/ClosedHH Zee 1.wav",
        "./Drums/Hihat/ClosedHH Zee 2.wav",
        "./Drums/Hihat/ClsdHH Can 1.wav",
        "./Drums/Hihat/ClsdHH Can 2.wav",
        "./Drums/Hihat/ClsdHH Function 1.wav",
        "./Drums/Hihat/ClsdHH Function 2.wav",
        "./Drums/Hihat/ClsdHH Otherwood 1.wav",
        "./Drums/Hihat/ClsdHH Otherwood 2.wav",
        "./Drums/Hihat/ClsdHH PrisonerS 1.wav",
        "./Drums/Hihat/ClsdHH PrisonerS 2.wav",
        "./Drums/Hihat/ClsdHH Uebertonez 1.wav",
        "./Drums/Hihat/ClsdHH Uebertonez 2.wav",
        "./Drums/Hihat/OpenHH Aberlour.wav",
        "./Drums/Hihat/OpenHH Antimax.wav",
        "./Drums/Hihat/OpenHH Beach.wav",
        "./Drums/Hihat/OpenHH Berg.wav",
        "./Drums/Hihat/OpenHH Betaine.wav",
        "./Drums/Hihat/OpenHH Bon Voyage.wav",
        "./Drums/Hihat/OpenHH Brownie.wav",
        "./Drums/Hihat/OpenHH Bueh.wav",
        "./Drums/Hihat/OpenHH Can.wav",
        "./Drums/Hihat/OpenHH Data.wav",
        "./Drums/Hihat/OpenHH Fruit.wav",
        "./Drums/Hihat/OpenHH Function.wav",
        "./Drums/Hihat/OpenHH Geiger.wav",
        "./Drums/Hihat/OpenHH Globuli.wav",
        "./Drums/Hihat/OpenHH MmmKay.wav",
        "./Drums/Hihat/OpenHH Moon.wav",
        "./Drums/Hihat/OpenHH Normandy.wav",
        "./Drums/Hihat/OpenHH Otherwood.wav",
        "./Drums/Hihat/OpenHH Pre-Fade.wav",
        "./Drums/Hihat/OpenHH PrisonerS.wav",
        "./Drums/Hihat/OpenHH Quarter.wav",
        "./Drums/Hihat/OpenHH Runzel.wav",
        "./Drums/Hihat/OpenHH Salad.wav",
        "./Drums/Hihat/OpenHH Schrumpf.wav",
        "./Drums/Hihat/OpenHH Singleton.wav",
        "./Drums/Hihat/OpenHH Strom.wav",
        "./Drums/Hihat/OpenHH Together.wav",
        "./Drums/Hihat/OpenHH Uebertonez.wav",
        "./Drums/Hihat/OpenHH XOR.wav",
        "./Drums/Hihat/OpenHH Zee.wav",
        "./Drums/Kick",
        "./Drums/Kick/Kick Aberlour 1.wav",
        "./Drums/Kick/Kick Aberlour 2.wav",
        "./Drums/Kick/Kick Aberlour Sub.wav",
        "./Drums/Kick/Kick Antimax 01.wav",
        "./Drums/Kick/Kick Antimax 02.wav",
        "./Drums/Kick/Kick Antimax Sub.wav",
        "./Drums/Kick/Kick Beach 1.wav",
        "./Drums/Kick/Kick Beach 2.wav",
        "./Drums/Kick/Kick Beach Sub.wav",
        "./Drums/Kick/Kick Berg 1.wav",
        "./Drums/Kick/Kick Berg 2.wav",
        "./Drums/Kick/Kick Berg Sub.wav",
        "./Drums/Kick/Kick Betaine 1.wav",
        "./Drums/Kick/Kick Betaine 2.wav",
        "./Drums/Kick/Kick Betaine 3.wav",
        "./Drums/Kick/Kick Bon Voyage 1.wav",
        "./Drums/Kick/Kick Bon Voyage 2.wav",
        "./Drums/Kick/Kick Bon Voyage Sub.wav",
        "./Drums/Kick/Kick Brownie 1.wav",
        "./Drums/Kick/Kick Brownie 2.wav",
        "./Drums/Kick/Kick Brownie Sub.wav",
        "./Drums/Kick/Kick Bueh 1.wav",
        "./Drums/Kick/Kick Bueh 2.wav",
        "./Drums/Kick/Kick Bueh 3.wav",
        "./Drums/Kick/Kick Can 1.wav",
        "./Drums/Kick/Kick Can 2.wav",
        "./Drums/Kick/Kick Can 3.wav",
        "./Drums/Kick/Kick Data 1.wav",
        "./Drums/Kick/Kick Data 2.wav",
        "./Drums/Kick/Kick Data 3.wav",
        "./Drums/Kick/Kick Fruit 1.wav",
        "./Drums/Kick/Kick Fruit 2.wav",
        "./Drums/Kick/Kick Fruit 3.wav",
        "./Drums/Kick/Kick Function 1.wav",
        "./Drums/Kick/Kick Function 2.wav",
        "./Drums/Kick/Kick Function 3.wav",
        "./Drums/Kick/Kick Geiger 1.wav",
        "./Drums/Kick/Kick Geiger 2.wav",
        "./Drums/Kick/Kick Geiger 3.wav",
        "./Drums/Kick/Kick Globuli 01.wav",
        "./Drums/Kick/Kick Globuli 02.wav",
        "./Drums/Kick/Kick Globuli Sub.wav",
        "./Drums/Kick/Kick MmmKay 1.wav",
        "./Drums/Kick/Kick MmmKay 2.wav",
        "./Drums/Kick/Kick MmmKay 3.wav",
        "./Drums/Kick/Kick Moon 1.wav",
        "./Drums/Kick/Kick Moon 2.wav",
        "./Drums/Kick/Kick Moon 3.wav",
        "./Drums/Kick/Kick Normandy 1.wav",
        "./Drums/Kick/Kick Normandy 2.wav",
        "./Drums/Kick/Kick Normandy Sub.wav",
        "./Drums/Kick/Kick Otherwood 1.wav",
        "./Drums/Kick/Kick Otherwood 2.wav",
        "./Drums/Kick/Kick Otherwood Sub.wav",
        "./Drums/Kick/Kick Pre-Fade 1.wav",
        "./Drums/Kick/Kick Pre-Fade 2.wav",
        "./Drums/Kick/Kick Pre-Fade Sub.wav",
        "./Drums/Kick/Kick PrisonerS 1.wav",
        "./Drums/Kick/Kick PrisonerS 2.wav",
        "./Drums/Kick/Kick PrisonerS 3.wav",
        "./Drums/Kick/Kick Quarter 1.wav",
        "./Drums/Kick/Kick Quarter 2.wav",
        "./Drums/Kick/Kick Quarter Sub.wav",
        "./Drums/Kick/Kick Runzel 1.wav",
        "./Drums/Kick/Kick Runzel 2.wav",
        "./Drums/Kick/Kick Runzel Sub.wav",
        "./Drums/Kick/Kick Salad 1.wav",
        "./Drums/Kick/Kick Salad 2.wav",
        "./Drums/Kick/Kick Salad 3.wav",
        "./Drums/Kick/Kick Schrumpf 1.wav",
        "./Drums/Kick/Kick Schrumpf 2.wav",
        "./Drums/Kick/Kick Schrumpf 3.wav",
        "./Drums/Kick/Kick Singleton 01.wav",
        "./Drums/Kick/Kick Singleton 02.wav",
        "./Drums/Kick/Kick Singleton Sub.wav",
        "./Drums/Kick/Kick Strom 1.wav",
        "./Drums/Kick/Kick Strom 2.wav",
        "./Drums/Kick/Kick Strom Sub.wav",
        "./Drums/Kick/Kick Together 1.wav",
        "./Drums/Kick/Kick Together 2.wav",
        "./Drums/Kick/Kick Together Sub.wav",
        "./Drums/Kick/Kick Uebertonez 1.wav",
        "./Drums/Kick/Kick Uebertonez 2.wav",
        "./Drums/Kick/Kick Uebertonez 3.wav",
        "./Drums/Kick/Kick XOR 1.wav",
        "./Drums/Kick/Kick XOR 2.wav",
        "./Drums/Kick/Kick XOR Sub.wav",
        "./Drums/Kick/Kick Zee 1.wav",
        "./Drums/Kick/Kick Zee 2.wav",
        "./Drums/Kick/Kick Zee Sub.wav",
        "./Drums/Mallet Drum",
        "./Drums/Mallet Drum/Mallet Can.wav",
        "./Drums/Mallet Drum/Mallet PrisonerS.wav",
        "./Drums/Mallet Drum/Mallet Runzel.wav",
        "./Drums/Mallet Drum/Mallet Uebertonez.wav",
        "./Drums/Percussion",
        "./Drums/Percussion/LoFill Aberlour.wav",
        "./Drums/Percussion/LoFill Antimax.wav",
        "./Drums/Percussion/LoFill Beach.wav",
        "./Drums/Percussion/LoFill Betaine.wav",
        "./Drums/Percussion/LoFill Bon Voyage.wav",
        "./Drums/Percussion/LoFill Bueh.wav",
        "./Drums/Percussion/LoFill Can.wav",
        "./Drums/Percussion/LoFill Data.wav",
        "./Drums/Percussion/LoFill Function 1.wav",
        "./Drums/Percussion/LoFill Function 2.wav",
        "./Drums/Percussion/LoFill Geiger.wav",
        "./Drums/Percussion/LoFill Globuli.wav",
        "./Drums/Percussion/LoFill MmmKay.wav",
        "./Drums/Percussion/LoFill Moon.wav",
        "./Drums/Percussion/LoFill Normandy.wav",
        "./Drums/Percussion/LoFill Otherwood.wav",
        "./Drums/Percussion/LoFill Pre-Fade.wav",
        "./Drums/Percussion/LoFill Quarter.wav",
        "./Drums/Percussion/LoFill Runzel.wav",
        "./Drums/Percussion/LoFill Salad.wav",
        "./Drums/Percussion/LoFill Schrumpf.wav",
        "./Drums/Percussion/LoFill Singleton.wav",
        "./Drums/Percussion/LoFill Strom.wav",
        "./Drums/Percussion/LoFill Together.wav",
        "./Drums/Percussion/LoFill Uebertonez.wav",
        "./Drums/Percussion/LoFill XOR.wav",
        "./Drums/Percussion/LoFill Zee.wav",
        "./Drums/Percussion/Perc Aberlour 1.wav",
        "./Drums/Percussion/Perc Aberlour 2.wav",
        "./Drums/Percussion/Perc Aberlour 3.wav",
        "./Drums/Percussion/Perc Aberlour 4.wav",
        "./Drums/Percussion/Perc Antimax 01.wav",
        "./Drums/Percussion/Perc Antimax 02.wav",
        "./Drums/Percussion/Perc Antimax 03.wav",
        "./Drums/Percussion/Perc Antimax 04.wav",
        "./Drums/Percussion/Perc Antimax 05.wav",
        "./Drums/Percussion/Perc Beach 1.wav",
        "./Drums/Percussion/Perc Beach 2.wav",
        "./Drums/Percussion/Perc Beach 3.wav",
        "./Drums/Percussion/Perc Beach 4.wav",
        "./Drums/Percussion/Perc Beach 5.wav",
        "./Drums/Percussion/Perc Berg 1.wav",
        "./Drums/Percussion/Perc Berg 2.wav",
        "./Drums/Percussion/Perc Berg 3.wav",
        "./Drums/Percussion/Perc Berg 4.wav",
        "./Drums/Percussion/Perc Betaine 1.wav",
        "./Drums/Percussion/Perc Betaine 2.wav",
        "./Drums/Percussion/Perc Betaine 3.wav",
        "./Drums/Percussion/Perc Betaine 4.wav",
        "./Drums/Percussion/Perc Betaine 5.wav",
        "./Drums/Percussion/Perc Bon Voyage 1.wav",
        "./Drums/Percussion/Perc Bon Voyage 2.wav",
        "./Drums/Percussion/Perc Bon Voyage 3.wav",
        "./Drums/Percussion/Perc Bon Voyage 4.wav",
        "./Drums/Percussion/Perc Brownie 1.wav",
        "./Drums/Percussion/Perc Brownie 2.wav",
        "./Drums/Percussion/Perc Brownie 3.wav",
        "./Drums/Percussion/Perc Brownie 4.wav",
        "./Drums/Percussion/Perc Brownie 5.wav",
        "./Drums/Percussion/Perc Bueh 1.wav",
        "./Drums/Percussion/Perc Bueh 2.wav",
        "./Drums/Percussion/Perc Bueh 3.wav",
        "./Drums/Percussion/Perc Bueh 4.wav",
        "./Drums/Percussion/Perc Bueh 5.wav",
        "./Drums/Percussion/Perc Can 1.wav",
        "./Drums/Percussion/Perc Can 2.wav",
        "./Drums/Percussion/Perc Can 3.wav",
        "./Drums/Percussion/Perc Can 4.wav",
        "./Drums/Percussion/Perc Data 1.wav",
        "./Drums/Percussion/Perc Data 2.wav",
        "./Drums/Percussion/Perc Data 3.wav",
        "./Drums/Percussion/Perc Data 4.wav",
        "./Drums/Percussion/Perc Data 5.wav",
        "./Drums/Percussion/Perc Function 1.wav",
        "./Drums/Percussion/Perc Function 2.wav",
        "./Drums/Percussion/Perc Function 3.wav",
        "./Drums/Percussion/Perc Function 4.wav",
        "./Drums/Percussion/Perc Geiger 1.wav",
        "./Drums/Percussion/Perc Geiger 2.wav",
        "./Drums/Percussion/Perc Geiger 3.wav",
        "./Drums/Percussion/Perc Geiger 4.wav",
        "./Drums/Percussion/Perc Geiger 5.wav",
        "./Drums/Percussion/Perc Globuli 01.wav",
        "./Drums/Percussion/Perc Globuli 02.wav",
        "./Drums/Percussion/Perc Globuli 03.wav",
        "./Drums/Percussion/Perc Globuli 04.wav",
        "./Drums/Percussion/Perc Globuli 05.wav",
        "./Drums/Percussion/Perc MmmKay 1.wav",
        "./Drums/Percussion/Perc MmmKay 2.wav",
        "./Drums/Percussion/Perc MmmKay 3.wav",
        "./Drums/Percussion/Perc MmmKay 4.wav",
        "./Drums/Percussion/Perc MmmKay 5.wav",
        "./Drums/Percussion/Perc Moon 1.wav",
        "./Drums/Percussion/Perc Moon 2.wav",
        "./Drums/Percussion/Perc Moon 3.wav",
        "./Drums/Percussion/Perc Moon 4.wav",
        "./Drums/Percussion/Perc Moon 5.wav",
        "./Drums/Percussion/Perc Normandy.wav",
        "./Drums/Percussion/Perc Otherwood 1.wav",
        "./Drums/Percussion/Perc Otherwood 2.wav",
        "./Drums/Percussion/Perc Otherwood 3.wav",
        "./Drums/Percussion/Perc Otherwood 4.wav",
        "./Drums/Percussion/Perc Otherwood 5.wav",
        "./Drums/Percussion/Perc Pre-Fade 1.wav",
        "./Drums/Percussion/Perc Pre-Fade 2.wav",
        "./Drums/Percussion/Perc Pre-Fade 3.wav",
        "./Drums/Percussion/Perc Pre-Fade 4.wav",
        "./Drums/Percussion/Perc PrisonerS 1.wav",
        "./Drums/Percussion/Perc PrisonerS 2.wav",
        "./Drums/Percussion/Perc PrisonerS 3.wav",
        "./Drums/Percussion/Perc Quarter 1.wav",
        "./Drums/Percussion/Perc Quarter 2.wav",
        "./Drums/Percussion/Perc Quarter 3.wav",
        "./Drums/Percussion/Perc Quarter 4.wav",
        "./Drums/Percussion/Perc Quarter 5.wav",
        "./Drums/Percussion/Perc Runzel 1.wav",
        "./Drums/Percussion/Perc Runzel 2.wav",
        "./Drums/Percussion/Perc Runzel 3.wav",
        "./Drums/Percussion/Perc Runzel 4.wav",
        "./Drums/Percussion/Perc Salad 1.wav",
        "./Drums/Percussion/Perc Salad 2.wav",
        "./Drums/Percussion/Perc Salad 3.wav",
        "./Drums/Percussion/Perc Salad 4.wav",
        "./Drums/Percussion/Perc Salad 5.wav",
        "./Drums/Percussion/Perc Schrumpf 1.wav",
        "./Drums/Percussion/Perc Schrumpf 2.wav",
        "./Drums/Percussion/Perc Schrumpf 3.wav",
        "./Drums/Percussion/Perc Schrumpf 4.wav",
        "./Drums/Percussion/Perc Schrumpf 5.wav",
        "./Drums/Percussion/Perc Singleton 01.wav",
        "./Drums/Percussion/Perc Singleton 02.wav",
        "./Drums/Percussion/Perc Singleton 03.wav",
        "./Drums/Percussion/Perc Singleton 04.wav",
        "./Drums/Percussion/Perc Singleton 05.wav",
        "./Drums/Percussion/Perc Strom 1.wav",
        "./Drums/Percussion/Perc Strom 2.wav",
        "./Drums/Percussion/Perc Strom 3.wav",
        "./Drums/Percussion/Perc Strom 4.wav",
        "./Drums/Percussion/Perc Together 1.wav",
        "./Drums/Percussion/Perc Together 2.wav",
        "./Drums/Percussion/Perc Together 3.wav",
        "./Drums/Percussion/Perc Together 4.wav",
        "./Drums/Percussion/Perc Uebertonez 1.wav",
        "./Drums/Percussion/Perc Uebertonez 2.wav",
        "./Drums/Percussion/Perc Uebertonez 3.wav",
        "./Drums/Percussion/Perc XOR 1.wav",
        "./Drums/Percussion/Perc XOR 2.wav",
        "./Drums/Percussion/Perc XOR 3.wav",
        "./Drums/Percussion/Perc XOR 4.wav",
        "./Drums/Percussion/Perc XOR 5.wav",
        "./Drums/Percussion/Perc Zee 1.wav",
        "./Drums/Percussion/Perc Zee 2.wav",
        "./Drums/Percussion/Perc Zee 3.wav",
        "./Drums/Percussion/Rim Fruit.wav",
        "./Drums/Shaker",
        "./Drums/Shaker/Shaker Aberlour.wav",
        "./Drums/Shaker/Shaker Beach.wav",
        "./Drums/Shaker/Shaker Berg.wav",
        "./Drums/Shaker/Shaker Betaine.wav",
        "./Drums/Shaker/Shaker Bon Voyage.wav",
        "./Drums/Shaker/Shaker Brownie.wav",
        "./Drums/Shaker/Shaker Bueh.wav",
        "./Drums/Shaker/Shaker Can.wav",
        "./Drums/Shaker/Shaker Data.wav",
        "./Drums/Shaker/Shaker Function.wav",
        "./Drums/Shaker/Shaker Geiger.wav",
        "./Drums/Shaker/Shaker Globuli 01.wav",
        "./Drums/Shaker/Shaker Globuli 02.wav",
        "./Drums/Shaker/Shaker MmmKay.wav",
        "./Drums/Shaker/Shaker Normandy 1.wav",
        "./Drums/Shaker/Shaker Normandy 2.wav",
        "./Drums/Shaker/Shaker Otherwood.wav",
        "./Drums/Shaker/Shaker Pre-Fade.wav",
        "./Drums/Shaker/Shaker PrisonerS.wav",
        "./Drums/Shaker/Shaker Quarter.wav",
        "./Drums/Shaker/Shaker Runzel.wav",
        "./Drums/Shaker/Shaker Salad.wav",
        "./Drums/Shaker/Shaker Schrumpf.wav",
        "./Drums/Shaker/Shaker Singleton.wav",
        "./Drums/Shaker/Shaker Strom.wav",
        "./Drums/Shaker/Shaker Together.wav",
        "./Drums/Shaker/Shaker Uebertonez.wav",
        "./Drums/Shaker/Shaker Zee.wav",
        "./Drums/Snare",
        "./Drums/Snare/Snare Aberlour 1.wav",
        "./Drums/Snare/Snare Aberlour 2.wav",
        "./Drums/Snare/Snare Antimax 01.wav",
        "./Drums/Snare/Snare Antimax 02.wav",
        "./Drums/Snare/Snare Beach 1.wav",
        "./Drums/Snare/Snare Beach 2.wav",
        "./Drums/Snare/Snare Berg 1.wav",
        "./Drums/Snare/Snare Berg 2.wav",
        "./Drums/Snare/Snare Betaine 1.wav",
        "./Drums/Snare/Snare Betaine 2.wav",
        "./Drums/Snare/Snare Bon Voyage 1.wav",
        "./Drums/Snare/Snare Bon Voyage 2.wav",
        "./Drums/Snare/Snare Brownie 1.wav",
        "./Drums/Snare/Snare Brownie 2.wav",
        "./Drums/Snare/Snare Bueh 1.wav",
        "./Drums/Snare/Snare Bueh 2.wav",
        "./Drums/Snare/Snare Can 1.wav",
        "./Drums/Snare/Snare Can 2.wav",
        "./Drums/Snare/Snare Data 1.wav",
        "./Drums/Snare/Snare Data 2.wav",
        "./Drums/Snare/Snare Fruit 1.wav",
        "./Drums/Snare/Snare Fruit 2.wav",
        "./Drums/Snare/Snare Function 1.wav",
        "./Drums/Snare/Snare Function 2.wav",
        "./Drums/Snare/Snare Geiger 1.wav",
        "./Drums/Snare/Snare Geiger 2.wav",
        "./Drums/Snare/Snare Globuli 01.wav",
        "./Drums/Snare/Snare Globuli 02.wav",
        "./Drums/Snare/Snare MmmKay.wav",
        "./Drums/Snare/Snare Moon 1.wav",
        "./Drums/Snare/Snare Moon 2.wav",
        "./Drums/Snare/Snare Normandy 1.wav",
        "./Drums/Snare/Snare Normandy 2.wav",
        "./Drums/Snare/Snare Otherwood 1.wav",
        "./Drums/Snare/Snare Otherwood 2.wav",
        "./Drums/Snare/Snare Pre-Fade 1.wav",
        "./Drums/Snare/Snare Pre-Fade 2.wav",
        "./Drums/Snare/Snare PrisonerS 1.wav",
        "./Drums/Snare/Snare PrisonerS 2.wav",
        "./Drums/Snare/Snare Quarter 1.wav",
        "./Drums/Snare/Snare Quarter 2.wav",
        "./Drums/Snare/Snare Runzel 1.wav",
        "./Drums/Snare/Snare Runzel 2.wav",
        "./Drums/Snare/Snare Salad 1.wav",
        "./Drums/Snare/Snare Salad 2.wav",
        "./Drums/Snare/Snare Schrumpf 1.wav",
        "./Drums/Snare/Snare Schrumpf 2.wav",
        "./Drums/Snare/Snare Singleton 01.wav",
        "./Drums/Snare/Snare Singleton 02.wav",
        "./Drums/Snare/Snare Strom 1.wav",
        "./Drums/Snare/Snare Strom 2.wav",
        "./Drums/Snare/Snare Together 1.wav",
        "./Drums/Snare/Snare Together 2.wav",
        "./Drums/Snare/Snare Uebertonez 1.wav",
        "./Drums/Snare/Snare Uebertonez 2.wav",
        "./Drums/Snare/Snare Uebertonez 3.wav",
        "./Drums/Snare/Snare XOR 1.wav",
        "./Drums/Snare/Snare XOR 2.wav",
        "./Drums/Snare/Snare Zee 1.wav",
        "./Drums/Snare/Snare Zee 2.wav",
        "./Drums/Tom",
        "./Drums/Tom/Tom Fruit 1.wav",
        "./Drums/Tom/Tom Fruit 2.wav",
        "./Drums/Tom/Tom Fruit 3.wav",
        "./Instruments",
        "./Instruments/Bass",
        "./Instruments/Bass/Bontempo",
        "./Instruments/Bass/Bontempo/Bontempo A2.wav",
        "./Instruments/Bass/Bontempo/Bontempo A3.wav",
        "./Instruments/Bass/Bontempo/Bontempo A4.wav",
        "./Instruments/Bass/Bontempo/Bontempo A5.wav",
        "./Instruments/Bass/Bontempo/Bontempo C3.wav",
        "./Instruments/Bass/Bontempo/Bontempo C4.wav",
        "./Instruments/Bass/Bontempo/Bontempo C5.wav",
        "./Instruments/Bass/Bontempo/Bontempo C6.wav",
        "./Instruments/Bass/Bontempo/Bontempo D#2.wav",
        "./Instruments/Bass/Bontempo/Bontempo D#3.wav",
        "./Instruments/Bass/Bontempo/Bontempo D#4.wav",
        "./Instruments/Bass/Bontempo/Bontempo D#5.wav",
        "./Instruments/Bass/Bontempo/Bontempo F#2.wav",
        "./Instruments/Bass/Bontempo/Bontempo F#3.wav",
        "./Instruments/Bass/Bontempo/Bontempo F#4.wav",
        "./Instruments/Bass/Bontempo/Bontempo F#5.wav",
        "./Instruments/Bass/Cohesion",
        "./Instruments/Bass/Cohesion/Cohesion A2.wav",
        "./Instruments/Bass/Cohesion/Cohesion A3.wav",
        "./Instruments/Bass/Cohesion/Cohesion A4.wav",
        "./Instruments/Bass/Cohesion/Cohesion A5.wav",
        "./Instruments/Bass/Cohesion/Cohesion C2.wav",
        "./Instruments/Bass/Cohesion/Cohesion C3.wav",
        "./Instruments/Bass/Cohesion/Cohesion C4.wav",
        "./Instruments/Bass/Cohesion/Cohesion C5.wav",
        "./Instruments/Bass/Cohesion/Cohesion D#2.wav",
        "./Instruments/Bass/Cohesion/Cohesion D#3.wav",
        "./Instruments/Bass/Cohesion/Cohesion D#4.wav",
        "./Instruments/Bass/Cohesion/Cohesion D#5.wav",
        "./Instruments/Bass/Cohesion/Cohesion F#2.wav",
        "./Instruments/Bass/Cohesion/Cohesion F#3.wav",
        "./Instruments/Bass/Cohesion/Cohesion F#4.wav",
        "./Instruments/Bass/Cohesion/Cohesion F#5.wav",
        "./Instruments/Bass/Dirac",
        "./Instruments/Bass/Dirac/Dirac A1.wav",
        "./Instruments/Bass/Dirac/Dirac A2.wav",
        "./Instruments/Bass/Dirac/Dirac A3.wav",
        "./Instruments/Bass/Dirac/Dirac A4.wav",
        "./Instruments/Bass/Dirac/Dirac A5.wav",
        "./Instruments/Bass/Dirac/Dirac C1.wav",
        "./Instruments/Bass/Dirac/Dirac C2.wav",
        "./Instruments/Bass/Dirac/Dirac C3.wav",
        "./Instruments/Bass/Dirac/Dirac C4.wav",
        "./Instruments/Bass/Dirac/Dirac C5.wav",
        "./Instruments/Bass/Dirac/Dirac D#1.wav",
        "./Instruments/Bass/Dirac/Dirac D#2.wav",
        "./Instruments/Bass/Dirac/Dirac D#3.wav",
        "./Instruments/Bass/Dirac/Dirac D#4.wav",
        "./Instruments/Bass/Dirac/Dirac D#5.wav",
        "./Instruments/Bass/Dirac/Dirac F#1.wav",
        "./Instruments/Bass/Dirac/Dirac F#2.wav",
        "./Instruments/Bass/Dirac/Dirac F#3.wav",
        "./Instruments/Bass/Dirac/Dirac F#4.wav",
        "./Instruments/Bass/Dirac/Dirac F#5.wav",
        "./Instruments/Bass/Error Code",
        "./Instruments/Bass/Error Code/Error Code A1.wav",
        "./Instruments/Bass/Error Code/Error Code A2.wav",
        "./Instruments/Bass/Error Code/Error Code A3.wav",
        "./Instruments/Bass/Error Code/Error Code C1.wav",
        "./Instruments/Bass/Error Code/Error Code C2.wav",
        "./Instruments/Bass/Error Code/Error Code C3.wav",
        "./Instruments/Bass/Error Code/Error Code D#1.wav",
        "./Instruments/Bass/Error Code/Error Code D#2.wav",
        "./Instruments/Bass/Error Code/Error Code D#3.wav",
        "./Instruments/Bass/Error Code/Error Code F#1.wav",
        "./Instruments/Bass/Error Code/Error Code F#2.wav",
        "./Instruments/Bass/Error Code/Error Code F#3.wav",
        "./Instruments/Bass/Fallout",
        "./Instruments/Bass/Fallout/Fallout A2.wav",
        "./Instruments/Bass/Fallout/Fallout A3.wav",
        "./Instruments/Bass/Fallout/Fallout A4.wav",
        "./Instruments/Bass/Fallout/Fallout A5.wav",
        "./Instruments/Bass/Fallout/Fallout C2.wav",
        "./Instruments/Bass/Fallout/Fallout C3.wav",
        "./Instruments/Bass/Fallout/Fallout C4.wav",
        "./Instruments/Bass/Fallout/Fallout C5.wav",
        "./Instruments/Bass/Fallout/Fallout D#2.wav",
        "./Instruments/Bass/Fallout/Fallout D#3.wav",
        "./Instruments/Bass/Fallout/Fallout D#4.wav",
        "./Instruments/Bass/Fallout/Fallout D#5.wav",
        "./Instruments/Bass/Fallout/Fallout F#2.wav",
        "./Instruments/Bass/Fallout/Fallout F#3.wav",
        "./Instruments/Bass/Fallout/Fallout F#4.wav",
        "./Instruments/Bass/Fallout/Fallout F#5.wav",
        "./Instruments/Bass/Gogettue",
        "./Instruments/Bass/Gogettue/Gogettue B1.wav",
        "./Instruments/Bass/Gogettue/Gogettue B2.wav",
        "./Instruments/Bass/Gogettue/Gogettue B3.wav",
        "./Instruments/Bass/Gogettue/Gogettue B4.wav",
        "./Instruments/Bass/Gogettue/Gogettue B5.wav",
        "./Instruments/Bass/Gogettue/Gogettue D2.wav",
        "./Instruments/Bass/Gogettue/Gogettue D3.wav",
        "./Instruments/Bass/Gogettue/Gogettue D4.wav",
        "./Instruments/Bass/Gogettue/Gogettue D5.wav",
        "./Instruments/Bass/Gogettue/Gogettue D6.wav",
        "./Instruments/Bass/Gogettue/Gogettue F1.wav",
        "./Instruments/Bass/Gogettue/Gogettue F2.wav",
        "./Instruments/Bass/Gogettue/Gogettue F3.wav",
        "./Instruments/Bass/Gogettue/Gogettue F4.wav",
        "./Instruments/Bass/Gogettue/Gogettue F5.wav",
        "./Instruments/Bass/Gogettue/Gogettue G#1.wav",
        "./Instruments/Bass/Gogettue/Gogettue G#2.wav",
        "./Instruments/Bass/Gogettue/Gogettue G#3.wav",
        "./Instruments/Bass/Gogettue/Gogettue G#4.wav",
        "./Instruments/Bass/Gogettue/Gogettue G#5.wav",
        "./Instruments/Bass/Ruebycon",
        "./Instruments/Bass/Ruebycon/Ruebycon A1.wav",
        "./Instruments/Bass/Ruebycon/Ruebycon A2.wav",
        "./Instruments/Bass/Ruebycon/Ruebycon A3.wav",
        "./Instruments/Bass/Ruebycon/Ruebycon A4.wav",
        "./Instruments/Bass/Ruebycon/Ruebycon A5.wav",
        "./Instruments/Bass/Ruebycon/Ruebycon A6.wav",
        "./Instruments/Bass/Ruebycon/Ruebycon C1.wav",
        "./Instruments/Bass/Ruebycon/Ruebycon C2.wav",
        "./Instruments/Bass/Ruebycon/Ruebycon C3.wav",
        "./Instruments/Bass/Ruebycon/Ruebycon C4.wav",
        "./Instruments/Bass/Ruebycon/Ruebycon C5.wav",
        "./Instruments/Bass/Ruebycon/Ruebycon C6.wav",
        "./Instruments/Bass/Ruebycon/Ruebycon D#1.wav",
        "./Instruments/Bass/Ruebycon/Ruebycon D#2.wav",
        "./Instruments/Bass/Ruebycon/Ruebycon D#3.wav",
        "./Instruments/Bass/Ruebycon/Ruebycon D#4.wav",
        "./Instruments/Bass/Ruebycon/Ruebycon D#5.wav",
        "./Instruments/Bass/Ruebycon/Ruebycon D#6.wav",
        "./Instruments/Bass/Ruebycon/Ruebycon F#1.wav",
        "./Instruments/Bass/Ruebycon/Ruebycon F#2.wav",
        "./Instruments/Bass/Ruebycon/Ruebycon F#3.wav",
        "./Instruments/Bass/Ruebycon/Ruebycon F#4.wav",
        "./Instruments/Bass/Ruebycon/Ruebycon F#5.wav",
        "./Instruments/Bass/Ruebycon/Ruebycon F#6.wav",
        "./Instruments/Bass/Scalar",
        "./Instruments/Bass/Scalar/Scalar A2.wav",
        "./Instruments/Bass/Scalar/Scalar A3.wav",
        "./Instruments/Bass/Scalar/Scalar A4.wav",
        "./Instruments/Bass/Scalar/Scalar C2.wav",
        "./Instruments/Bass/Scalar/Scalar C3.wav",
        "./Instruments/Bass/Scalar/Scalar C4.wav",
        "./Instruments/Bass/Scalar/Scalar C5.wav",
        "./Instruments/Bass/Scalar/Scalar D#2.wav",
        "./Instruments/Bass/Scalar/Scalar D#3.wav",
        "./Instruments/Bass/Scalar/Scalar D#4.wav",
        "./Instruments/Bass/Scalar/Scalar D#5.wav",
        "./Instruments/Bass/Scalar/Scalar F#2.wav",
        "./Instruments/Bass/Scalar/Scalar F#3.wav",
        "./Instruments/Bass/Scalar/Scalar F#4.wav",
        "./Instruments/Bass/Scalar/Scalar F#5.wav",
        "./Instruments/Bass/Shoveler",
        "./Instruments/Bass/Shoveler/Shoveler A2.wav",
        "./Instruments/Bass/Shoveler/Shoveler A3.wav",
        "./Instruments/Bass/Shoveler/Shoveler A4.wav",
        "./Instruments/Bass/Shoveler/Shoveler A5.wav",
        "./Instruments/Bass/Shoveler/Shoveler C2.wav",
        "./Instruments/Bass/Shoveler/Shoveler C3.wav",
        "./Instruments/Bass/Shoveler/Shoveler C4.wav",
        "./Instruments/Bass/Shoveler/Shoveler C5.wav",
        "./Instruments/Bass/Shoveler/Shoveler D#2.wav",
        "./Instruments/Bass/Shoveler/Shoveler D#3.wav",
        "./Instruments/Bass/Shoveler/Shoveler D#4.wav",
        "./Instruments/Bass/Shoveler/Shoveler D#5.wav",
        "./Instruments/Bass/Shoveler/Shoveler F#2.wav",
        "./Instruments/Bass/Shoveler/Shoveler F#3.wav",
        "./Instruments/Bass/Shoveler/Shoveler F#4.wav",
        "./Instruments/Bass/Shoveler/Shoveler F#5.wav",
        "./Instruments/Bass/Totalistic",
        "./Instruments/Bass/Totalistic/Totalistic A2.wav",
        "./Instruments/Bass/Totalistic/Totalistic A3.wav",
        "./Instruments/Bass/Totalistic/Totalistic A4.wav",
        "./Instruments/Bass/Totalistic/Totalistic A5.wav",
        "./Instruments/Bass/Totalistic/Totalistic C2.wav",
        "./Instruments/Bass/Totalistic/Totalistic C3.wav",
        "./Instruments/Bass/Totalistic/Totalistic C4.wav",
        "./Instruments/Bass/Totalistic/Totalistic C5.wav",
        "./Instruments/Bass/Totalistic/Totalistic D#2.wav",
        "./Instruments/Bass/Totalistic/Totalistic D#3.wav",
        "./Instruments/Bass/Totalistic/Totalistic D#4.wav",
        "./Instruments/Bass/Totalistic/Totalistic D#5.wav",
        "./Instruments/Bass/Totalistic/Totalistic F#2.wav",
        "./Instruments/Bass/Totalistic/Totalistic F#3.wav",
        "./Instruments/Bass/Totalistic/Totalistic F#4.wav",
        "./Instruments/Bass/Totalistic/Totalistic F#5.wav",
        "./Instruments/Lead",
        "./Instruments/Lead/Anaerobic",
        "./Instruments/Lead/Anaerobic/Anaerobic A1.wav",
        "./Instruments/Lead/Anaerobic/Anaerobic A2.wav",
        "./Instruments/Lead/Anaerobic/Anaerobic A3.wav",
        "./Instruments/Lead/Anaerobic/Anaerobic C2.wav",
        "./Instruments/Lead/Anaerobic/Anaerobic C3.wav",
        "./Instruments/Lead/Anaerobic/Anaerobic C4.wav",
        "./Instruments/Lead/Anaerobic/Anaerobic D#2.wav",
        "./Instruments/Lead/Anaerobic/Anaerobic D#3.wav",
        "./Instruments/Lead/Anaerobic/Anaerobic D#4.wav",
        "./Instruments/Lead/Anaerobic/Anaerobic F#2.wav",
        "./Instruments/Lead/Anaerobic/Anaerobic F#3.wav",
        "./Instruments/Lead/Anaerobic/Anaerobic F#4.wav",
        "./Instruments/Lead/Beirut",
        "./Instruments/Lead/Beirut/Beirut A1.wav",
        "./Instruments/Lead/Beirut/Beirut A2.wav",
        "./Instruments/Lead/Beirut/Beirut A3.wav",
        "./Instruments/Lead/Beirut/Beirut A4.wav",
        "./Instruments/Lead/Beirut/Beirut C2.wav",
        "./Instruments/Lead/Beirut/Beirut C3.wav",
        "./Instruments/Lead/Beirut/Beirut C4.wav",
        "./Instruments/Lead/Beirut/Beirut D#1.wav",
        "./Instruments/Lead/Beirut/Beirut D#2.wav",
        "./Instruments/Lead/Beirut/Beirut D#3.wav",
        "./Instruments/Lead/Beirut/Beirut D#4.wav",
        "./Instruments/Lead/Beirut/Beirut F#1.wav",
        "./Instruments/Lead/Beirut/Beirut F#2.wav",
        "./Instruments/Lead/Beirut/Beirut F#3.wav",
        "./Instruments/Lead/Beirut/Beirut F#4.wav",
        "./Instruments/Lead/Cassata",
        "./Instruments/Lead/Cassata/Cassata A2.wav",
        "./Instruments/Lead/Cassata/Cassata A3.wav",
        "./Instruments/Lead/Cassata/Cassata A4.wav",
        "./Instruments/Lead/Cassata/Cassata A5.wav",
        "./Instruments/Lead/Cassata/Cassata C2.wav",
        "./Instruments/Lead/Cassata/Cassata C3.wav",
        "./Instruments/Lead/Cassata/Cassata C4.wav",
        "./Instruments/Lead/Cassata/Cassata C5.wav",
        "./Instruments/Lead/Cassata/Cassata D#2.wav",
        "./Instruments/Lead/Cassata/Cassata D#3.wav",
        "./Instruments/Lead/Cassata/Cassata D#4.wav",
        "./Instruments/Lead/Cassata/Cassata D#5.wav",
        "./Instruments/Lead/Cassata/Cassata F#2.wav",
        "./Instruments/Lead/Cassata/Cassata F#3.wav",
        "./Instruments/Lead/Cassata/Cassata F#4.wav",
        "./Instruments/Lead/Cassata/Cassata F#5.wav",
        "./Instruments/Lead/Circularism",
        "./Instruments/Lead/Circularism/Circularism A#2.wav",
        "./Instruments/Lead/Circularism/Circularism A#3.wav",
        "./Instruments/Lead/Circularism/Circularism A#4.wav",
        "./Instruments/Lead/Circularism/Circularism C#2.wav",
        "./Instruments/Lead/Circularism/Circularism C#3.wav",
        "./Instruments/Lead/Circularism/Circularism C#4.wav",
        "./Instruments/Lead/Circularism/Circularism E2.wav",
        "./Instruments/Lead/Circularism/Circularism E3.wav",
        "./Instruments/Lead/Circularism/Circularism E4.wav",
        "./Instruments/Lead/Circularism/Circularism G2.wav",
        "./Instruments/Lead/Circularism/Circularism G3.wav",
        "./Instruments/Lead/Circularism/Circularism G4.wav",
        "./Instruments/Lead/Delta Curve",
        "./Instruments/Lead/Delta Curve/Delta Curve A1.wav",
        "./Instruments/Lead/Delta Curve/Delta Curve A2.wav",
        "./Instruments/Lead/Delta Curve/Delta Curve A3.wav",
        "./Instruments/Lead/Delta Curve/Delta Curve A4.wav",
        "./Instruments/Lead/Delta Curve/Delta Curve C1.wav",
        "./Instruments/Lead/Delta Curve/Delta Curve C2.wav",
        "./Instruments/Lead/Delta Curve/Delta Curve C3.wav",
        "./Instruments/Lead/Delta Curve/Delta Curve C4.wav",
        "./Instruments/Lead/Delta Curve/Delta Curve D#1.wav",
        "./Instruments/Lead/Delta Curve/Delta Curve D#2.wav",
        "./Instruments/Lead/Delta Curve/Delta Curve D#3.wav",
        "./Instruments/Lead/Delta Curve/Delta Curve D#4.wav",
        "./Instruments/Lead/Delta Curve/Delta Curve F#1.wav",
        "./Instruments/Lead/Delta Curve/Delta Curve F#2.wav",
        "./Instruments/Lead/Delta Curve/Delta Curve F#3.wav",
        "./Instruments/Lead/Delta Curve/Delta Curve F#4.wav",
        "./Instruments/Lead/Dweller",
        "./Instruments/Lead/Dweller/Dweller A2.wav",
        "./Instruments/Lead/Dweller/Dweller A3.wav",
        "./Instruments/Lead/Dweller/Dweller A4.wav",
        "./Instruments/Lead/Dweller/Dweller A5.wav",
        "./Instruments/Lead/Dweller/Dweller C2.wav",
        "./Instruments/Lead/Dweller/Dweller C3.wav",
        "./Instruments/Lead/Dweller/Dweller C4.wav",
        "./Instruments/Lead/Dweller/Dweller C5.wav",
        "./Instruments/Lead/Dweller/Dweller D#2.wav",
        "./Instruments/Lead/Dweller/Dweller D#3.wav",
        "./Instruments/Lead/Dweller/Dweller D#4.wav",
        "./Instruments/Lead/Dweller/Dweller D#5.wav",
        "./Instruments/Lead/Dweller/Dweller F#2.wav",
        "./Instruments/Lead/Dweller/Dweller F#3.wav",
        "./Instruments/Lead/Dweller/Dweller F#4.wav",
        "./Instruments/Lead/Dweller/Dweller F#5.wav",
        "./Instruments/Lead/Echnatone",
        "./Instruments/Lead/Echnatone/Echnatone A2.wav",
        "./Instruments/Lead/Echnatone/Echnatone A3.wav",
        "./Instruments/Lead/Echnatone/Echnatone A4.wav",
        "./Instruments/Lead/Echnatone/Echnatone A5.wav",
        "./Instruments/Lead/Echnatone/Echnatone C2.wav",
        "./Instruments/Lead/Echnatone/Echnatone C3.wav",
        "./Instruments/Lead/Echnatone/Echnatone C4.wav",
        "./Instruments/Lead/Echnatone/Echnatone C5.wav",
        "./Instruments/Lead/Echnatone/Echnatone D#2.wav",
        "./Instruments/Lead/Echnatone/Echnatone D#3.wav",
        "./Instruments/Lead/Echnatone/Echnatone D#4.wav",
        "./Instruments/Lead/Echnatone/Echnatone D#5.wav",
        "./Instruments/Lead/Echnatone/Echnatone F#2.wav",
        "./Instruments/Lead/Echnatone/Echnatone F#3.wav",
        "./Instruments/Lead/Echnatone/Echnatone F#4.wav",
        "./Instruments/Lead/Echnatone/Echnatone F#5.wav",
        "./Instruments/Lead/Ethifier",
        "./Instruments/Lead/Ethifier/Ethifier A2.wav",
        "./Instruments/Lead/Ethifier/Ethifier A3.wav",
        "./Instruments/Lead/Ethifier/Ethifier A4.wav",
        "./Instruments/Lead/Ethifier/Ethifier A5.wav",
        "./Instruments/Lead/Ethifier/Ethifier C2.wav",
        "./Instruments/Lead/Ethifier/Ethifier C3.wav",
        "./Instruments/Lead/Ethifier/Ethifier C4.wav",
        "./Instruments/Lead/Ethifier/Ethifier C5.wav",
        "./Instruments/Lead/Ethifier/Ethifier D#2.wav",
        "./Instruments/Lead/Ethifier/Ethifier D#3.wav",
        "./Instruments/Lead/Ethifier/Ethifier D#4.wav",
        "./Instruments/Lead/Ethifier/Ethifier D#5.wav",
        "./Instruments/Lead/Ethifier/Ethifier F#2.wav",
        "./Instruments/Lead/Ethifier/Ethifier F#3.wav",
        "./Instruments/Lead/Ethifier/Ethifier F#4.wav",
        "./Instruments/Lead/Ethifier/Ethifier F#5.wav",
        "./Instruments/Lead/Harmotron",
        "./Instruments/Lead/Harmotron/Harmotron A0.wav",
        "./Instruments/Lead/Harmotron/Harmotron A1.wav",
        "./Instruments/Lead/Harmotron/Harmotron A2.wav",
        "./Instruments/Lead/Harmotron/Harmotron A3.wav",
        "./Instruments/Lead/Harmotron/Harmotron A4.wav",
        "./Instruments/Lead/Harmotron/Harmotron C1.wav",
        "./Instruments/Lead/Harmotron/Harmotron C3.wav",
        "./Instruments/Lead/Harmotron/Harmotron C4.wav",
        "./Instruments/Lead/Harmotron/Harmotron C5.wav",
        "./Instruments/Lead/Harmotron/Harmotron D#1.wav",
        "./Instruments/Lead/Harmotron/Harmotron D#2.wav",
        "./Instruments/Lead/Harmotron/Harmotron D#3.wav",
        "./Instruments/Lead/Harmotron/Harmotron D#4.wav",
        "./Instruments/Lead/Harmotron/Harmotron D2.wav",
        "./Instruments/Lead/Harmotron/Harmotron F#1.wav",
        "./Instruments/Lead/Harmotron/Harmotron F#2.wav",
        "./Instruments/Lead/Harmotron/Harmotron F#3.wav",
        "./Instruments/Lead/Harmotron/Harmotron F#4.wav",
        "./Instruments/Lead/Schmoof",
        "./Instruments/Lead/Schmoof/Schmoof A2.wav",
        "./Instruments/Lead/Schmoof/Schmoof A3.wav",
        "./Instruments/Lead/Schmoof/Schmoof A4.wav",
        "./Instruments/Lead/Schmoof/Schmoof C2.wav",
        "./Instruments/Lead/Schmoof/Schmoof C3.wav",
        "./Instruments/Lead/Schmoof/Schmoof C4.wav",
        "./Instruments/Lead/Schmoof/Schmoof D#2.wav",
        "./Instruments/Lead/Schmoof/Schmoof D#3.wav",
        "./Instruments/Lead/Schmoof/Schmoof D#4.wav",
        "./Instruments/Lead/Schmoof/Schmoof F#2.wav",
        "./Instruments/Lead/Schmoof/Schmoof F#3.wav",
        "./Instruments/Lead/Schmoof/Schmoof F#4.wav",
        "./Loops",
        "./Loops/Construction",
        "./Loops/Construction/Aberlour",
        "./Loops/Construction/Aberlour/Chord[121] E Aberlour.wav",
        "./Loops/Construction/Aberlour/Chord[121] F# Aberlour.wav",
        "./Loops/Construction/Aberlour/Drums[121] Aberlour 1.wav",
        "./Loops/Construction/Aberlour/Drums[121] Aberlour 2.wav",
        "./Loops/Construction/Aberlour/Full[121] E Aberlour.wav",
        "./Loops/Construction/Aberlour/Full[121] F# Aberlour.wav",
        "./Loops/Construction/Aberlour/Kick[121] Aberlour.wav",
        "./Loops/Construction/Aberlour/Shaker[121] Aberlour.wav",
        "./Loops/Construction/Aberlour/Snare[121] Aberlour.wav",
        "./Loops/Construction/Antimax",
        "./Loops/Construction/Antimax/Bass[121] F# Antimax.wav",
        "./Loops/Construction/Antimax/Drums[121] Antimax 1.wav",
        "./Loops/Construction/Antimax/Drums[121] Antimax 2.wav",
        "./Loops/Construction/Antimax/Drums[121] Antimax 3.wav",
        "./Loops/Construction/Antimax/Full[121] F# Antimax.wav",
        "./Loops/Construction/Antimax/Kick[121] Antimax.wav",
        "./Loops/Construction/Antimax/Perc[121] Antimax.wav",
        "./Loops/Construction/Beaching",
        "./Loops/Construction/Beaching/Clap[121] Beaching.wav",
        "./Loops/Construction/Beaching/Combo[121] D# Beaching.wav",
        "./Loops/Construction/Beaching/Drums[121] Beaching 1.wav",
        "./Loops/Construction/Beaching/Drums[121] Beaching 2.wav",
        "./Loops/Construction/Beaching/HiHats[121] Beaching 1.wav",
        "./Loops/Construction/Beaching/HiHats[121] Beaching 2.wav",
        "./Loops/Construction/Beaching/Kick[121] Beaching.wav",
        "./Loops/Construction/Bergbau",
        "./Loops/Construction/Bergbau/Clap[121] Bergbau.wav",
        "./Loops/Construction/Bergbau/Drums[121] Bergbau 1.wav",
        "./Loops/Construction/Bergbau/Drums[121] Bergbau 2.wav",
        "./Loops/Construction/Bergbau/HiHats[121] Bergbau 1.wav",
        "./Loops/Construction/Bergbau/HiHats[121] Bergbau 2.wav",
        "./Loops/Construction/Bergbau/Kick[121] Bergbau.wav",
        "./Loops/Construction/Bergbau/SFX[121] Bergbau.wav",
        "./Loops/Construction/Bergbau/Shaker[121] Bergbau.wav",
        "./Loops/Construction/Betaine",
        "./Loops/Construction/Betaine/Chord[121] E Betaine.wav",
        "./Loops/Construction/Betaine/Clap[121] Betaine.wav",
        "./Loops/Construction/Betaine/Combo[121] D Betaine.wav",
        "./Loops/Construction/Betaine/Drums[121] Betaine.wav",
        "./Loops/Construction/Betaine/Full[121] C# Betaine.wav",
        "./Loops/Construction/Betaine/Full[121] E Betaine.wav",
        "./Loops/Construction/Betaine/HiHats[121] Betaine.wav",
        "./Loops/Construction/Betaine/Kick[121] Betaine.wav",
        "./Loops/Construction/Bit XOR",
        "./Loops/Construction/Bit XOR/Drums[121] Bit 1.wav",
        "./Loops/Construction/Bit XOR/Drums[121] Bit 2.wav",
        "./Loops/Construction/Bit XOR/Glitch[121] Bit.wav",
        "./Loops/Construction/Bit XOR/HiHats[121] Bit.wav",
        "./Loops/Construction/Bit XOR/Kick[121] Bit 1.wav",
        "./Loops/Construction/Bit XOR/Kick[121] Bit 2.wav",
        "./Loops/Construction/Bit XOR/SFX[121] Bit.wav",
        "./Loops/Construction/Bit XOR/Snare[121] Bit.wav",
        "./Loops/Construction/Bon Voyage",
        "./Loops/Construction/Bon Voyage/Chord[121] A# Voyage.wav",
        "./Loops/Construction/Bon Voyage/Drums[121] Voyage 1.wav",
        "./Loops/Construction/Bon Voyage/Drums[121] Voyage 2.wav",
        "./Loops/Construction/Bon Voyage/Full[121] A# Voyage.wav",
        "./Loops/Construction/Bon Voyage/Full[121] F Voyage.wav",
        "./Loops/Construction/Bon Voyage/HiHats[121] Voyage.wav",
        "./Loops/Construction/Bon Voyage/Kick[121] Voyage 1.wav",
        "./Loops/Construction/Bon Voyage/Kick[121] Voyage 2.wav",
        "./Loops/Construction/Bon Voyage/Perc[121] Voyage.wav",
        "./Loops/Construction/Brownie",
        "./Loops/Construction/Brownie/Clap[121] Brownie.wav",
        "./Loops/Construction/Brownie/Cowbell[121] Brownie.wav",
        "./Loops/Construction/Brownie/Drums[121] Brownie 1.wav",
        "./Loops/Construction/Brownie/Drums[121] Brownie 2.wav",
        "./Loops/Construction/Brownie/Drums[121] Brownie 3.wav",
        "./Loops/Construction/Brownie/Full[121] F# Brownie.wav",
        "./Loops/Construction/Brownie/HiHats[121] Brownie.wav",
        "./Loops/Construction/Brownie/Kick[121] Brownie.wav",
        "./Loops/Construction/Brownie/Perc[121] Brownie.wav",
        "./Loops/Construction/Can Opener",
        "./Loops/Construction/Can Opener/Cowbell[121] Opener.wav",
        "./Loops/Construction/Can Opener/Drums[121] Opener 1.wav",
        "./Loops/Construction/Can Opener/Drums[121] Opener 2.wav",
        "./Loops/Construction/Can Opener/Drums[121] Opener 3.wav",
        "./Loops/Construction/Can Opener/Kick[121] Opener.wav",
        "./Loops/Construction/Can Opener/Perc[121] Opener.wav",
        "./Loops/Construction/Data Riot",
        "./Loops/Construction/Data Riot/Clap[121] DataRiot.wav",
        "./Loops/Construction/Data Riot/Drums[121] DataRiot 1.wav",
        "./Loops/Construction/Data Riot/Drums[121] DataRiot 2.wav",
        "./Loops/Construction/Data Riot/Drums[121] DataRiot 3.wav",
        "./Loops/Construction/Data Riot/HiHats[121] DataRiot.wav",
        "./Loops/Construction/Data Riot/Kick[121] DataRiot 1.wav",
        "./Loops/Construction/Data Riot/Kick[121] DataRiot 2.wav",
        "./Loops/Construction/Data Riot/Perc[121] DataRiot.wav",
        "./Loops/Construction/Fruit",
        "./Loops/Construction/Fruit/Clap[121] Fruit.wav",
        "./Loops/Construction/Fruit/Drums[121] Fruit 1.wav",
        "./Loops/Construction/Fruit/Drums[121] Fruit 2.wav",
        "./Loops/Construction/Fruit/Kick[121] Fruit 1.wav",
        "./Loops/Construction/Fruit/Kick[121] Fruit 2.wav",
        "./Loops/Construction/Fruit/Ride[121] Fruit.wav",
        "./Loops/Construction/Fruit/Rim[121] Fruit.wav",
        "./Loops/Construction/Fruit/Snare[121] Fruit.wav",
        "./Loops/Construction/Fruit/Stab[121] Fruit.wav",
        "./Loops/Construction/Fruit/Tom[121] Fruit.wav",
        "./Loops/Construction/Function Two",
        "./Loops/Construction/Function Two/Drums[121] FunctionTwo 1.wav",
        "./Loops/Construction/Function Two/Drums[121] FunctionTwo 2.wav",
        "./Loops/Construction/Function Two/Drums[121] FunctionTwo 3.wav",
        "./Loops/Construction/Function Two/HiHats[121] FunctionTwo 1.wav",
        "./Loops/Construction/Function Two/HiHats[121] FunctionTwo 2.wav",
        "./Loops/Construction/Function Two/Kick[121] FunctionTwo.wav",
        "./Loops/Construction/Function Two/Perc[121] FunctionTwo.wav",
        "./Loops/Construction/Function Two/Snare[121] FunctionTwo.wav",
        "./Loops/Construction/Funk Salad",
        "./Loops/Construction/Funk Salad/Drums[121] FunkSalad 1.wav",
        "./Loops/Construction/Funk Salad/Drums[121] FunkSalad 2.wav",
        "./Loops/Construction/Funk Salad/Full[121] D# FunkSalad.wav",
        "./Loops/Construction/Funk Salad/HiHats[121] FunkSalad.wav",
        "./Loops/Construction/Funk Salad/Kick[121] FunkSalad 1.wav",
        "./Loops/Construction/Funk Salad/Kick[121] FunkSalad 2.wav",
        "./Loops/Construction/Funk Salad/Perc[121] FunkSalad.wav",
        "./Loops/Construction/Funk Salad/Snare[121] FunkSalad.wav",
        "./Loops/Construction/Funk Salad/Tom[121] FunkSalad.wav",
        "./Loops/Construction/Globuli",
        "./Loops/Construction/Globuli/Drums[121] Globuli 1.wav",
        "./Loops/Construction/Globuli/Drums[121] Globuli 2.wav",
        "./Loops/Construction/Globuli/Drums[121] Globuli 3.wav",
        "./Loops/Construction/Globuli/HiHats[121] Globuli.wav",
        "./Loops/Construction/Globuli/Kick[121] Globuli 1.wav",
        "./Loops/Construction/Globuli/Kick[121] Globuli 2.wav",
        "./Loops/Construction/Globuli/Perc[121] Globuli 1.wav",
        "./Loops/Construction/Globuli/Perc[121] Globuli 2.wav",
        "./Loops/Construction/Kount Geiger",
        "./Loops/Construction/Kount Geiger/Combo[121] F Geiger.wav",
        "./Loops/Construction/Kount Geiger/Drums[121] Geiger 1.wav",
        "./Loops/Construction/Kount Geiger/Drums[121] Geiger 2.wav",
        "./Loops/Construction/Kount Geiger/Full[121] F Geiger.wav",
        "./Loops/Construction/Kount Geiger/HiHats[121] Geiger.wav",
        "./Loops/Construction/Kount Geiger/Kick[121] Geiger 1.wav",
        "./Loops/Construction/Kount Geiger/Kick[121] Geiger 2.wav",
        "./Loops/Construction/Kount Geiger/Perc[121] Geiger.wav",
        "./Loops/Construction/MmmKay",
        "./Loops/Construction/MmmKay/Clap[121] MmmKay.wav",
        "./Loops/Construction/MmmKay/Drums[121] MmmKay.wav",
        "./Loops/Construction/MmmKay/HiHats[121] MmmKay 1.wav",
        "./Loops/Construction/MmmKay/HiHats[121] MmmKay 2.wav",
        "./Loops/Construction/MmmKay/Kick[121] MmmKay 1.wav",
        "./Loops/Construction/MmmKay/Kick[121] MmmKay 2.wav",
        "./Loops/Construction/MmmKay/Perc[121] MmmKay.wav",
        "./Loops/Construction/MmmKay/Shaker[121] MmmKay.wav",
        "./Loops/Construction/MmmKay/Snare[121] MmmKay.wav",
        "./Loops/Construction/Monsieur Bueh",
        "./Loops/Construction/Monsieur Bueh/Combo[121] Bueh.wav",
        "./Loops/Construction/Monsieur Bueh/Drums[121] Bueh 1.wav",
        "./Loops/Construction/Monsieur Bueh/Drums[121] Bueh 2.wav",
        "./Loops/Construction/Monsieur Bueh/HiHats[121] Bueh.wav",
        "./Loops/Construction/Monsieur Bueh/Kick[121] Bueh 1.wav",
        "./Loops/Construction/Monsieur Bueh/Kick[121] Bueh 2.wav",
        "./Loops/Construction/Monsieur Bueh/Shaker[121] Bueh.wav",
        "./Loops/Construction/Monsieur Bueh/Snare[121] Bueh.wav",
        "./Loops/Construction/Moonjuice",
        "./Loops/Construction/Moonjuice/Bass[121] B Moonjuice.wav",
        "./Loops/Construction/Moonjuice/Drums[121] Moonjuice 1.wav",
        "./Loops/Construction/Moonjuice/Drums[121] Moonjuice 2.wav",
        "./Loops/Construction/Moonjuice/Full[121] B Moonjuice.wav",
        "./Loops/Construction/Moonjuice/HiHats[121] Moonjuice 1.wav",
        "./Loops/Construction/Moonjuice/HiHats[121] Moonjuice 2.wav",
        "./Loops/Construction/Moonjuice/Kick[121] Moonjuice.wav",
        "./Loops/Construction/Moonjuice/Perc[121] Moonjuice.wav",
        "./Loops/Construction/No Prisoners",
        "./Loops/Construction/No Prisoners/Clave[121] NoPrisoners.wav",
        "./Loops/Construction/No Prisoners/Combo[121] B NoPrisoners.wav",
        "./Loops/Construction/No Prisoners/Drums[121] NoPrisoners.wav",
        "./Loops/Construction/No Prisoners/Full[121] B NoPrisoners.wav",
        "./Loops/Construction/No Prisoners/Kick[121] NoPrisoners 1.wav",
        "./Loops/Construction/No Prisoners/Kick[121] NoPrisoners 2.wav",
        "./Loops/Construction/No Prisoners/Perc[121] NoPrisoners.wav",
        "./Loops/Construction/No Prisoners/Shaker[121] NoPrisoners.wav",
        "./Loops/Construction/No Prisoners/Snare[121] NoPrisoners.wav",
        "./Loops/Construction/Normandy",
        "./Loops/Construction/Normandy/Chord[121] F# Normandy.wav",
        "./Loops/Construction/Normandy/Clap[121] Normandy.wav",
        "./Loops/Construction/Normandy/Combo[121] Normandy.wav",
        "./Loops/Construction/Normandy/Drums[121] Normandy.wav",
        "./Loops/Construction/Normandy/Full[121] F# Normandy.wav",
        "./Loops/Construction/Normandy/HiHats[121] Normandy.wav",
        "./Loops/Construction/Normandy/Kick[121] Normandy 1.wav",
        "./Loops/Construction/Normandy/Kick[121] Normandy 2.wav",
        "./Loops/Construction/Otherwood",
        "./Loops/Construction/Otherwood/Combo[121] G Otherwood.wav",
        "./Loops/Construction/Otherwood/Drums[121] Otherwood.wav",
        "./Loops/Construction/Otherwood/Full[121] G Otherwood.wav",
        "./Loops/Construction/Otherwood/Kick[121] Otherwood.wav",
        "./Loops/Construction/Otherwood/Perc[121] Otherwood 1.wav",
        "./Loops/Construction/Otherwood/Perc[121] Otherwood 2.wav",
        "./Loops/Construction/Otherwood/Shaker[121] Otherwood.wav",
        "./Loops/Construction/Pre-Fade",
        "./Loops/Construction/Pre-Fade/Combo[121] A Pre-Fade.wav",
        "./Loops/Construction/Pre-Fade/Drums[121] Pre-Fade 1.wav",
        "./Loops/Construction/Pre-Fade/Drums[121] Pre-Fade 2.wav",
        "./Loops/Construction/Pre-Fade/Full[121] A Pre-Fade.wav",
        "./Loops/Construction/Pre-Fade/HiHats[121] Pre-Fade.wav",
        "./Loops/Construction/Pre-Fade/Perc[121] Pre-Fade.wav",
        "./Loops/Construction/Pre-Fade/Shaker[121] Pre-Fade.wav",
        "./Loops/Construction/Pre-Fade/Sub[121] A Pre-Fade.wav",
        "./Loops/Construction/Quartercast",
        "./Loops/Construction/Quartercast/Combo[121] Quartercast.wav",
        "./Loops/Construction/Quartercast/Drums[121] Quartecast 3.wav",
        "./Loops/Construction/Quartercast/Drums[121] Quartercast 1.wav",
        "./Loops/Construction/Quartercast/Drums[121] Quartercast 2.wav",
        "./Loops/Construction/Quartercast/HiHats[121] Quartercast.wav",
        "./Loops/Construction/Quartercast/Kick[121] Quartercast.wav",
        "./Loops/Construction/Quartercast/Perc[121] Quartercast.wav",
        "./Loops/Construction/Quartercast/Shaker[121] Quartercast.wav",
        "./Loops/Construction/Runzelberger",
        "./Loops/Construction/Runzelberger/Conga[121] Runzelberger.wav",
        "./Loops/Construction/Runzelberger/Drums[121] Runzelberger 1.wav",
        "./Loops/Construction/Runzelberger/Drums[121] Runzelberger 2.wav",
        "./Loops/Construction/Runzelberger/Drums[121] Runzelberger 3.wav",
        "./Loops/Construction/Runzelberger/Drums[121] Runzelberger 4.wav",
        "./Loops/Construction/Runzelberger/Drums[121] Runzelberger 5.wav",
        "./Loops/Construction/Runzelberger/HiHats[121] Runzelberger.wav",
        "./Loops/Construction/Runzelberger/Perc[121] Runzelberger.wav",
        "./Loops/Construction/Runzelberger/Shaker[121] Runzelberger.wav",
        "./Loops/Construction/Schrumpfkopf",
        "./Loops/Construction/Schrumpfkopf/Drums[121] Schrumpfkopf 1.wav",
        "./Loops/Construction/Schrumpfkopf/Drums[121] Schrumpfkopf 2.wav",
        "./Loops/Construction/Schrumpfkopf/Full[121] Schrumpfkopf.wav",
        "./Loops/Construction/Schrumpfkopf/HiHats[121] Schrumpfkopf.wav",
        "./Loops/Construction/Schrumpfkopf/Kick[121] Schrumpfkopf.wav",
        "./Loops/Construction/Schrumpfkopf/Perc[121] Schrumpfkopf.wav",
        "./Loops/Construction/Schrumpfkopf/SFX[121] Schrumpfkopf.wav",
        "./Loops/Construction/Schrumpfkopf/Tom[121] Schrumpfkopf.wav",
        "./Loops/Construction/Singleton",
        "./Loops/Construction/Singleton/Clap[121] Singleton 1.wav",
        "./Loops/Construction/Singleton/Clap[121] Singleton 2.wav",
        "./Loops/Construction/Singleton/Drums[121] Singleton 1.wav",
        "./Loops/Construction/Singleton/Drums[121] Singleton 2.wav",
        "./Loops/Construction/Singleton/Kick[121] Singleton.wav",
        "./Loops/Construction/Singleton/Perc[121] Singleton.wav",
        "./Loops/Construction/Singleton/Snare[121] Singleton.wav",
        "./Loops/Construction/Stromkasten",
        "./Loops/Construction/Stromkasten/Chord[121] A Stromkasten.wav",
        "./Loops/Construction/Stromkasten/Chord[121] A# Stromkasten.wav",
        "./Loops/Construction/Stromkasten/Clap[121] Stromkasten.wav",
        "./Loops/Construction/Stromkasten/Drums[121] Stromkasten 1.wav",
        "./Loops/Construction/Stromkasten/Drums[121] Stromkasten 2.wav",
        "./Loops/Construction/Stromkasten/Full[121] A Stromkasten.wav",
        "./Loops/Construction/Stromkasten/Full[121] A# Stromkasten.wav",
        "./Loops/Construction/Stromkasten/HiHats[121] Stromkasten.wav",
        "./Loops/Construction/Together",
        "./Loops/Construction/Together/Chord[121] B Together.wav",
        "./Loops/Construction/Together/Combo[121] B Together.wav",
        "./Loops/Construction/Together/Drums[121] Together 1.wav",
        "./Loops/Construction/Together/Drums[121] Together 2.wav",
        "./Loops/Construction/Together/Full[121] B Together.wav",
        "./Loops/Construction/Together/HiHats[121] Together.wav",
        "./Loops/Construction/Together/Kick[121] Together.wav",
        "./Loops/Construction/Together/Perc[121] Together.wav",
        "./Loops/Construction/Together/Shaker[121] Together.wav",
        "./Loops/Construction/Triple Zee",
        "./Loops/Construction/Triple Zee/Chord[121] F# Zee.wav",
        "./Loops/Construction/Triple Zee/Clave[121] Zee.wav",
        "./Loops/Construction/Triple Zee/Drums[121] Zee 1.wav",
        "./Loops/Construction/Triple Zee/Drums[121] Zee 2.wav",
        "./Loops/Construction/Triple Zee/Full[121] D# Zee.wav",
        "./Loops/Construction/Triple Zee/Full[121] F# Zee.wav",
        "./Loops/Construction/Triple Zee/Kick[121] Zee.wav",
        "./Loops/Construction/Triple Zee/Perc[121] Zee.wav",
        "./Loops/Construction/Triple Zee/Synth[121] D# Zee.wav",
        "./Loops/Construction/Uebertonez",
        "./Loops/Construction/Uebertonez/Drums[121] Uebertonez 1.wav",
        "./Loops/Construction/Uebertonez/Drums[121] Uebertonez 2.wav",
        "./Loops/Construction/Uebertonez/HiHats[121] Uebertonez 1.wav",
        "./Loops/Construction/Uebertonez/HiHats[121] Uebertonez 2.wav",
        "./Loops/Construction/Uebertonez/Kick[121] Uebertonez.wav",
        "./Loops/Construction/Uebertonez/Perc[121] Uebertonez.wav",
        "./Loops/Construction/Uebertonez/Synth[121] F# Uebertonez.wav",
        "./One Shots",
        "./One Shots/Ambience",
        "./One Shots/Ambience/Ambience Transistor 01.wav",
        "./One Shots/Ambience/Ambience Transistor 02.wav",
        "./One Shots/Analog FX",
        "./One Shots/Analog FX/Dive Berg.wav",
        "./One Shots/Analog FX/Dive Fruit.wav",
        "./One Shots/Analog FX/Dive PrisonerS 1.wav",
        "./One Shots/Analog FX/Dive PrisonerS 2.wav",
        "./One Shots/Analog FX/Dive Transistor 01.wav",
        "./One Shots/Analog FX/Dive Transistor 02.wav",
        "./One Shots/Analog FX/Dive Transistor 03.wav",
        "./One Shots/Analog FX/Rise Transistor 01.wav",
        "./One Shots/Analog FX/Rise Transistor 02.wav",
        "./One Shots/Analog FX/Rise Transistor 03.wav",
        "./One Shots/Analog FX/Rise Transistor 04.wav",
        "./One Shots/Analog FX/Rise Transistor 05.wav",
        "./One Shots/Analog FX/Squelch Transistor 01.wav",
        "./One Shots/Analog FX/Squelch Transistor 02.wav",
        "./One Shots/Analog FX/Squelch Transistor 03.wav",
        "./One Shots/Analog FX/Squelch Transistor 04.wav",
        "./One Shots/Analog FX/Squelch Transistor 05.wav",
        "./One Shots/Analog FX/Squelch Transistor 06.wav",
        "./One Shots/Analog FX/Squelch Transistor 07.wav",
        "./One Shots/Analog FX/Squelch Transistor 08.wav",
        "./One Shots/Analog FX/Squelch Transistor 09.wav",
        "./One Shots/Analog FX/Squelch Transistor 10.wav",
        "./One Shots/Analog FX/Squelch Transistor 11.wav",
        "./One Shots/Analog FX/Squelch Transistor 12.wav",
        "./One Shots/Analog FX/Squelch Transistor 13.wav",
        "./One Shots/Analog FX/Squelch Transistor 14.wav",
        "./One Shots/Analog FX/Squelch Transistor 15.wav",
        "./One Shots/Analog FX/Squelch Transistor 16.wav",
        "./One Shots/Analog FX/Squelch Transistor 17.wav",
        "./One Shots/Analog FX/Squelch Transistor 18.wav",
        "./One Shots/Analog FX/Squelch Transistor 19.wav",
        "./One Shots/Analog FX/Squelch Transistor 20.wav",
        "./One Shots/Analog FX/Squelch Transistor 21.wav",
        "./One Shots/Analog FX/Squelch Transistor 22.wav",
        "./One Shots/Analog FX/Squelch Transistor 23.wav",
        "./One Shots/Analog FX/Squelch Transistor 24.wav",
        "./One Shots/Analog FX/Squelch Transistor 25.wav",
        "./One Shots/Analog FX/Squelch Transistor 26.wav",
        "./One Shots/Analog FX/Squelch Transistor 27.wav",
        "./One Shots/Analog FX/Squelch Transistor 28.wav",
        "./One Shots/Analog FX/Squelch Transistor 29.wav",
        "./One Shots/Analog FX/Squelch Transistor 30.wav",
        "./One Shots/Analog FX/Squelch Transistor 31.wav",
        "./One Shots/Analog FX/Squelch Transistor 32.wav",
        "./One Shots/Analog FX/Squelch Transistor 33.wav",
        "./One Shots/Analog FX/Whoop Pre-fade.wav",
        "./One Shots/Analog FX/Wow Transistor 01.wav",
        "./One Shots/Analog FX/Wow Transistor 02.wav",
        "./One Shots/Analog FX/Wow Transistor 03.wav",
        "./One Shots/Blip & Blop",
        "./One Shots/Blip & Blop/Bleep Transistor 01.wav",
        "./One Shots/Blip & Blop/Bleep Transistor 02.wav",
        "./One Shots/Blip & Blop/Bleep Transistor 03.wav",
        "./One Shots/Blip & Blop/Bleep Transistor 04.wav",
        "./One Shots/Blip & Blop/Bleep Transistor 05.wav",
        "./One Shots/Blip & Blop/Bleep Transistor 06.wav",
        "./One Shots/Blip & Blop/Bleep Transistor 07.wav",
        "./One Shots/Blip & Blop/Bleep Zee.wav",
        "./One Shots/Buzz",
        "./One Shots/Buzz/Buzz Transistor 01.wav",
        "./One Shots/Buzz/Buzz Transistor 02.wav",
        "./One Shots/Buzz/Buzz Transistor 03.wav",
        "./One Shots/Buzz/Buzz Transistor 04.wav",
        "./One Shots/Chord",
        "./One Shots/Chord/Chord Aberlour.wav",
        "./One Shots/Chord/Chord Bon Voyage 1.wav",
        "./One Shots/Chord/Chord Bon Voyage 2.wav",
        "./One Shots/Chord/Chord Normandy.wav",
        "./One Shots/Chord/Chord Strom.wav",
        "./One Shots/Chord/Chord Together.wav",
        "./One Shots/Chord/Chord Transistor 01.wav",
        "./One Shots/Chord/Chord Transistor 02.wav",
        "./One Shots/Chord/Chord Transistor 03.wav",
        "./One Shots/Chord/Chord Transistor 04.wav",
        "./One Shots/Chord/Chord Transistor 05.wav",
        "./One Shots/Chord/Chord Transistor 06.wav",
        "./One Shots/Chord/Chord Transistor 07.wav",
        "./One Shots/Chord/Chord Transistor 08.wav",
        "./One Shots/Chord/Chord Transistor 09.wav",
        "./One Shots/Chord/Chord Transistor 10.wav",
        "./One Shots/Chord/Chord Transistor 11.wav",
        "./One Shots/Chord/Chord Transistor 12.wav",
        "./One Shots/Chord/Chord Transistor 13.wav",
        "./One Shots/Chord/Chord Transistor 14.wav",
        "./One Shots/Chord/Chord Transistor 15.wav",
        "./One Shots/Chord/Chord Transistor 16.wav",
        "./One Shots/Chord/Chord Transistor 17.wav",
        "./One Shots/Chord/Chord Transistor 18.wav",
        "./One Shots/Chord/Chord Transistor 19.wav",
        "./One Shots/Chord/Chord Zee.wav",
        "./One Shots/Glitch",
        "./One Shots/Glitch/Glitch Transistor 01.wav",
        "./One Shots/Glitch/Glitch Transistor 02.wav",
        "./One Shots/Glitch/Glitch Transistor 03.wav",
        "./One Shots/Glitch/Glitch Transistor 04.wav",
        "./One Shots/Glitch/Glitch Transistor 05.wav",
        "./One Shots/Glitch/Glitch Transistor 06.wav",
        "./One Shots/Glitch/Glitch Transistor 07.wav",
        "./One Shots/Glitch/Glitch Transistor 08.wav",
        "./One Shots/Glitch/Glitch Transistor 09.wav",
        "./One Shots/Glitch/Glitch Transistor 10.wav",
        "./One Shots/Impact",
        "./One Shots/Impact/Impact Normandy.wav",
        "./One Shots/Impact/Impact Transistor 01.wav",
        "./One Shots/Impact/Impact Transistor 02.wav",
        "./One Shots/Impact/Impact Transistor 03.wav",
        "./One Shots/Impact/Impact Transistor 04.wav",
        "./One Shots/Impact/Impact Transistor 05.wav",
        "./One Shots/Impact/Impact Transistor 06.wav",
        "./One Shots/Impact/Impact Transistor 07.wav",
        "./One Shots/Impact/Impact Transistor 08.wav",
        "./One Shots/Impact/Impact Transistor 09.wav",
        "./One Shots/Impact/Impact Transistor 10.wav",
        "./One Shots/Impact/Impact Transistor 11.wav",
        "./One Shots/Impact/Impact Transistor 12.wav",
        "./One Shots/Impact/Impact Transistor 13.wav",
        "./One Shots/Impact/Impact Transistor 14.wav",
        "./One Shots/Impact/Impact Transistor 15.wav",
        "./One Shots/Impact/Impact Transistor 16.wav",
        "./One Shots/Impact/Impact Transistor 17.wav",
        "./One Shots/Impact/Impact Transistor 18.wav",
        "./One Shots/Impact/Impact Transistor 19.wav",
        "./One Shots/Impact/Impact Transistor 20.wav",
        "./One Shots/Impact/Impact Transistor 21.wav",
        "./One Shots/Impact/Impact Transistor 22.wav",
        "./One Shots/Impact/Impact Transistor 23.wav",
        "./One Shots/Impact/Impact Transistor 24.wav",
        "./One Shots/Noise",
        "./One Shots/Noise/Noise Transistor 01.wav",
        "./One Shots/Noise/Noise Uebertonez.wav",
        "./One Shots/Sweep & Swell",
        "./One Shots/Sweep & Swell/Sweep Normandy.wav",
        "./One Shots/Sweep & Swell/Swell Transistor 01.wav",
        "./One Shots/Sweep & Swell/Swell Transistor 02.wav",
        "./One Shots/Sweep & Swell/Swell Transistor 03.wav",
        "./One Shots/Sweep & Swell/Swell Transistor 04.wav",
        "./One Shots/Sweep & Swell/Swoosh Transistor 01.wav",
        "./One Shots/Synth Note",
        "./One Shots/Synth Note/ResoSynth Transistor c#3 01.wav",
        "./One Shots/Synth Note/ResoSynth Transistor c#3 02.wav",
        "./One Shots/Synth Note/ResoSynth Transistor c#3 03.wav",
        "./One Shots/Synth Note/ResoSynth Transistor c#3 04.wav"
    ]


def get_real_audio_library_paths() -> List[Path]:
    """
    Returns the actual directory structure as Path objects.
    
    Returns:
        List[Path]: List of Path objects representing the file/directory structure
    """
    return [Path(path) for path in get_real_audio_library_structure()]


def get_real_audio_library_stats() -> Dict[str, Any]:
    """
    Returns statistics about the real audio library structure.
    
    Returns:
        Dict[str, Any]: Dictionary containing file counts, directory counts, etc.
    """
    paths = get_real_audio_library_paths()
    
    # Count files vs directories
    files = [p for p in paths if p.suffix.lower() in ['.wav', '.aif', '.mp3']]
    directories = [p for p in paths if not p.suffix]
    
    # Count by category
    drums_count = len([p for p in paths if 'Drums' in str(p)])
    instruments_count = len([p for p in paths if 'Instruments' in str(p)])
    loops_count = len([p for p in paths if 'Loops' in str(p)])
    one_shots_count = len([p for p in paths if 'One Shots' in str(p)])
    
    return {
        'total_paths': len(paths),
        'total_files': len(files),
        'total_directories': len(directories),
        'drums_count': drums_count,
        'instruments_count': instruments_count,
        'loops_count': loops_count,
        'one_shots_count': one_shots_count,
        'audio_files': [str(p) for p in files],
        'directories': [str(p) for p in directories]
    }


if __name__ == "__main__":
    # Print stats when run directly
    stats = get_real_audio_library_stats()
    print("Real Audio Library Structure Stats:")
    for key, value in stats.items():
        if key not in ['audio_files', 'directories']:
            print(f"  {key}: {value}")
    
    print(f"\nTotal audio files: {len(stats['audio_files'])}")
    print(f"Total directories: {len(stats['directories'])}")
